homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_k
  base_url: !secret base_u
  trusted_networks: 
    - 192.168.1.0/24
    - 172.0.0.1 
  # Uncomment this to add a password (recommended!)
  # api_password: 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - scene
      - automation

# View all events in a logbook
logbook:

# To enable logging for debugging purposes
logger:
  default: warning
  logs:
    #homeassistant.components.sector_alarm: debug
    #homeassistant.components.camera.generic: fatal
    homeassistant.components.vacuum: error
    miio.device: critical



# Track the sun
sun:
  - elevation
  - azimuth

# Weather prediction
sensor:
  - platform: yr
    name: "Väder"
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_cert_check 

  - platform: template
    sensors:
      vacuum_battery_level:
        friendly_name: 'Vacuum - Battery Level'
        value_template: "{{ states.vacuum.cleany.attributes.battery_level|default(-1)|int if states.vacuum.cleany is not none }}"
        unit_of_measurement: '%'
        icon_template: '{% if states.vacuum.cleany.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.vacuum.cleany.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.vacuum.cleany.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.vacuum.cleany.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.vacuum.cleany.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.vacuum.cleany.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.vacuum.cleany.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.vacuum.cleany.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.vacuum.cleany.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.vacuum.cleany.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           mdi:battery-outline
                        {% endif %}'
  - platform: template
    sensors:
      vacuum_side_brush_left:
        value_template: '{{  states.vacuum.cleany.attributes.side_brush_left }}'
        friendly_name: 'Side brush life left (hours)'

  - platform: template
    sensors:
      vacuum_cleaned_area:
        value_template: '{{  states.vacuum.cleany.attributes.cleaned_area }}'
        friendly_name: 'Last cleaned area (m2)'

  - platform: template
    sensors:
      vacuum_total_area:
        value_template: '{{  states.vacuum.cleany.attributes.total_cleaned_area }}'
        friendly_name: 'Lifetime cleaned area (m2)'

  - platform: template
    sensors:
      vacuum_status:
        value_template: '{{  states.vacuum.cleany.attributes.status }}'
        friendly_name: 'Vacuum status'

  - platform: template
    sensors:
      vacuum_do_not_disturb_start:
        value_template: '{{  states.vacuum.cleany.attributes.do_not_disturb_start }}'
        friendly_name: 'DnD start time'

  - platform: template
    sensors:
      vacuum_do_not_disturb_end:
        value_template: '{{  states.vacuum.cleany.attributes.do_not_disturb_end }}'
        friendly_name: 'DnD end time'

  - platform: template
    sensors:
      vacuum_cleaning_time:
        value_template: '{{  states.vacuum.cleany.attributes.cleaning_time }}'
        friendly_name: 'Last cleaning time (minutes)'

  - platform: template
    sensors:
      vacuum_filter_left:
        value_template: '{{  states.vacuum.cleany.attributes.filter_left }}'
        friendly_name: 'Filter life left (hours)'

  - platform: template
    sensors:
      vacuum_total_time:
        value_template: '{{  states.vacuum.cleany.attributes.total_cleaning_time }}'
        friendly_name: 'Lifetime cleaning time (minutes)'

  - platform: template
    sensors:
      vacuum_cleaning_count:
        value_template: '{{  states.vacuum.cleany.attributes.cleaning_count }}'
        friendly_name: 'Lifetime cleaning count'

  - platform: template
    sensors:
      vacuum_main_brush_left:
        value_template: '{{  states.vacuum.cleany.attributes.main_brush_left }}'
        friendly_name: 'Main Brush life left (hours)'

  - platform: template
    sensors:
      vacuum_do_not_disturb:
        value_template: '{{  states.vacuum.cleany.attributes.do_not_disturb }}'
        friendly_name: 'Do Not Disturb State'

  - platform: template
    sensors:
      vacuum_fan_speed:
        value_template: '{{  states.vacuum.cleany.attributes.fan_speed }}'
        friendly_name: 'Fan speed setting'
  

# Text to speech
tts:
  - platform: google

input_boolean:
  override_vardagsmorgon:
    name: Override vardagsmorgon
    initial: off
    icon: mdi:theater

binary_sensor:
  - platform: workday
    country: "NO"
  #- platform: template
  #  sensors:
  #    nagon_hemma_bin:
  #      friendly_name: "Någon hemma bin"
  #      device_class: presence
  #      entity_id:
  #        - device_tracker.anders_anders_owntracks
  #        - device_tracker.frida_frida_owntracks
  #        - device_tracker.anders_ping
  #        - device_tracker.frida_ping
  #        - alarm_control_panel.sector_alarm_02700305
  #      value_template: >-
  #        {{ (is_state('device_tracker.anders_anders_owntracks', 'home')
  #           or is_state('device_tracker.frida_frida_owntracks', 'home')
  #           or is_state('device_tracker.anders_ping', 'home')
  #           or is_state('device_tracker.frida_ping', 'home')
  #           or is_state('alarm_control_panel.sector_alarm_02700305', 'disarmed')) }}
  #    anders_hemma_bin:
  #      friendly_name: "Anders"
  #      device_class: presence
  #      entity_id:
  #        - device_tracker.anders_anders_owntracks
  #        - device_tracker.anders_ping
  #      value_template: >-
  #        {{ is_state('device_tracker.anders_anders_owntracks', 'home')
  #           or is_state('device_tracker.anders_ping', 'home') }}
  #    frida_hemma_bin:
  #      friendly_name: "Frida"
  #      device_class: presence
  #      entity_id:
  #        - device_tracker.frida_frida_owntracks
  #        - device_tracker.frida_ping
  #      value_template: >-
  #        {{ is_state('device_tracker.frida_frida_owntracks', 'home')
  #           or is_state('device_tracker.frida_ping', 'home') }}


# Scenes
scene: !include_dir_list scenes

group: !include groups.yaml

automation: !include_dir_list automations

# Vera
vera:
  vera_controller_url: !secret vera_url 

# Ikea trådfri
tradfri:
  host: !secret tradfri_ip
  allow_tradfri_groups: FALSE

# Controls
#input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml

media_player:
  - platform: sonos
  - platform: cast
  - platform: panasonic_viera
    host: !secret vieratv_ip
    mac: !secret vieratv_mac
    name: "Viera TV uppe"
  - platform: samsungtv
    host: !secret samsungtv_ip
    mac: !secret samsungtv_mac
    name: "Samsung TV nere"
 
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

ios:

device_tracker:
  - platform: ping
    track_new_devices: False
    consider_home: 180
    hosts:
      anders_ping: 192.168.1.133
      frida_ping: 192.168.1.134 
  - platform: owntracks
    max_gps_accuracy: 250
    discovery: enabled
    consider_home: 180
    track_new_devices: yes
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 10
    track_new_devices: yes

mqtt:
  broker: !secret mqtt_broker 
  port: !secret mqtt_port
  username: !secret mqtt_uname 
  password: !secret mqtt_password 

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    icon: mdi:domain
    radius: 100

map:

light:
  - platform: lifx

sector_alarm:
  email: !secret anders_email
  password: !secret secalarm_pword
  alarm_id: !secret secalarm_id 
  code: !secret secalarm_pin 
  thermometers: true 
  alarm_panel: true 

notify:
  - name: pushbullet 
    platform: pushbullet
    api_key: !secret pushbullet_api_token


shell_command: 
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

camera:
  - platform: mjpeg
    name: "Dlink uppe video"
    #still_image_url: !secret camera1_still_image_url
    mjpeg_url: !secret camera1_mjpeg_url
    username: !secret camera_uname
    password: !secret camera_passwd

switch:
  platform: command_line
  switches:
    dlink_uppe_motion:
      #command_on: !secret command_on 
      #command_off: !secret command_off
      #command_state: !secret command_state
      value_template: '{{ value == "1" }}'

google_assistant:
  project_id: !secret ga_project
  client_id: !secret ga_client_id 
  access_token: !secret ga_access_token
  api_key: !secret ga_homegraph_api_key
  exposed_by_default: false
  exposed_domains:
    - switch
    - light
    - scene
    - vacuum

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.151
    token: !secret xiaomi_token 
    name: "cleany" 