alias: "Alla borta"
trigger:
  #- platform: state
    #entity_id: input_boolean.someone_home
    #entity_id: binary_sensor.someone_home_bin
    #entity_id: binary_sensor.nagon_hemma_bin
    #from: 'on'
    #to: 'off'
  - platform: state
    entity_id: alarm_control_panel.sector_alarm_02700305
    #entity_id: input_boolean.secalarm_armedaway
    to: 'armed_away'
action:
  - service: homeassistant.turn_off
    entity_id:
      - group.julias_room
      - group.klaras_room
      - group.fa_room
      - group.upstairs_livingroom
      - group.downstairs_livingroom
      - group.kitchen
      - light.dimmer_hall_39
  - service: notify.pushbullet
    data:
      message: 'Alla borta'