alias: "Alla borta - bool"
trigger:
  platform: template
  #value_template: "{% if (is_state('device_tracker.anders_bengtphone','not_home')) and (is_state('device_tracker.frida_fridaphone','not_home')) %}true{% endif %}"
  #value_template: "{% if (is_state('device_tracker.anders_bengtphone','not_home')) and (is_state('device_tracker.frida_fridaphone','not_home')) and (is_state('device_tracker.frida_ping','not_home')) and (is_state('device_tracker.anders_ping','not_home')) and (is_state('device_tracker.anders_anders_owntracks','not_home')) %}true{% endif %}"
  value_template: "{% if (is_state('input_boolean.anders_hemma','off')) and (is_state('input_boolean.frida_hemma','off')) %}true{% endif %}"
condition:
  condition: state
  entity_id: input_boolean.someone_home
  state: 'on'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.someone_home