alias: "Alla borta"
trigger:
  - platform: state
    #entity_id: input_boolean.someone_home
    entity_id: binary_sensor.someone_home_bin
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.secalarm_armedaway
    #entity_id: input_boolean.secalarm_armedaway
    from: 'off'
    to: 'on'
action:
  service: homeassistant.turn_off
  entity_id:
    - group.julias_room
    - group.klaras_room
    - group.fa_room
    - group.upstairs_livingroom
    - group.downstairs_livingroom
    - group.kitchen