alias: "Anders kommer hem - bool"
trigger:
  platform: template
  value_template: "{% if (is_state('device_tracker.anders_ios','home')) or (is_state('device_tracker.anders_ping','home')) or (is_state('device_tracker.anders_anders_owntracks','home')) %}true{% endif %}"
condition:
  condition: state
  entity_id: input_boolean.anders_hemma
  state: 'off'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.anders_hemma