alias: Brightness TV nere
trigger:
  platform: state
  entity_id: input_number.brightness_tv_nere
action:
  service: light.turn_on
  data:
    entity_id:
      - light.dimmer_svarta_tavlan_5
      - light.dimmer_tavelvagg_tv_18
      - light.stora_bollen
      #- light.dimmer_hall_39
  data_template:
    brightness: '{{ states( "input_number.brightness_tv_nere" )|round( 0 ) }}'