alias: "Daligt väder - grundbelysning"
trigger: 
  platform: sun 
  event: sunset
  offset: -02:00:00 
condition: 
  condition: numeric_state
  entity_id: sensor.weather_cloudiness 
  above: "50" 
action: 
  service: scene.turn_on
  entity_id: scene.hus_grundbelysning 

