alias: 'Vacuum scheduling weekdays when everyone away'
trigger: 
  platform: time
  at: "10:00:00"
condition:
  condition: and 
  conditions:
    - condition: time 
      weekday:
      - mon
      - wed
      - fri
    - condition: state
      entity_id: alarm_control_panel.sector_alarm_02700305
      state: 'armed_away'
action: 
  - service: vacuum.turn_on
    entity_id: vacuum.cleany