# used for sending pushbullet notificatons when sensor switches to off
alias: "check bin sensor någon hemma - off"
trigger:
  - platform: state
    entity_id: binary_sensor.nagon_hemma_bin
    from: 'on'
    to: 'off'
action:
  service: notify.pushbullet
  data:
    message: 'nagon_hemma_bin - OFF'