alias: "Någon kommer hem"
trigger:
  platform: state
  entity_id: input_boolean.someone_home
  to: 'on'
condition:
  condition: time
  before: '22:00:00'
  after: '07:00:00'
action:
  service: scene.turn_on
  entity_id: scene.vardagsmorgon
