# used for sending pushbullet notificatons when sensor switches to on
alias: "check bin sensor någon hemma - on"
trigger:
  - platform: state
    entity_id: binary_sensor.nagon_hemma_bin
    from: 'off'
    to: 'on'
action:
  service: notify.pushbullet
  data:
    message: 'nagon_hemma_bin - ON'