alias: "Alarm påkopplat - bortaläge"
trigger:
  platform: state
  entity_id: alarm_control_panel.sector_alarm_02700305
  to: 'armed_away'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.secalarm_armedaway
  - service: input_boolean.turn_off
    entity_id: input_boolean.secalarm_armedhome
  - service: input_boolean.turn_off
    entity_id: input_boolean.secalarm_disarmed
  